CREATE OR REPLACE VIEW DOSTEPNE_WYCIECZKI_VIEW AS
SELECT w.NAZWA,
       w.KRAJ,
       w.DATA,
       w.LICZBA_MIEJSC,
       w.LICZBA_WOLNYCH_MIEJSC
FROM WYCIECZKI_MIEJSCA w
WHERE w.DATA > CURRENT_DATE
  AND w.LICZBA_WOLNYCH_MIEJSC > 0;
