SELECT * FROM UCZESTNICY_WYCIECZKI(7);
SELECT * FROM REZERWACJE_OSOBY(23);

SELECT * FROM dostepne_wycieczki_function('POLSKA', CURRENT_DATE, CURRENT_DATE + 190000)

BEGIN
    dodaj_rezerwacje(8, 41);
END;
