create schema APP;

create table CATEGORY
(
	CATEGORYID INTEGER not null
		primary key,
	NAME VARCHAR(255)
);

create table INVOICE
(
	INVOICENUMBER INTEGER not null
		primary key,
	QUANTITY INTEGER not null
);

create table PRODUCTS
(
	PRODUCTID INTEGER not null
		primary key,
	PRODUCTNAME VARCHAR(255),
	UNITSONSTOCK INTEGER not null,
	CATEGORYID INTEGER
		constraint FKMGOP3YOCT41Q8YD7DPFMYI1EN
			references CATEGORY (CATEGORYID)
);

create table INVOICE_PRODUCTS
(
	CANBESOLDIN_INVOICENUMBER INTEGER not null
		constraint FKRC271LI7RMOOHR5U1IK6AEXLH
			references INVOICE (INVOICENUMBER),
	INCLUDESPRODUCTS_PRODUCTID INTEGER not null
		constraint FK5QBA1N5MM1AEP8VASAO57GQCP
			references PRODUCTS (PRODUCTID),
	primary key (CANBESOLDIN_INVOICENUMBER, INCLUDESPRODUCTS_PRODUCTID)
);

create table SUPPLIERS
(
	SUPPLIERID INTEGER not null
		primary key,
	CITY VARCHAR(255),
	COMPANYNAME VARCHAR(255),
	STREET VARCHAR(255)
);

create table PRODUCTSUPPLIER
(
	SUPPLIERID INTEGER not null
		constraint FKHVXVPX6PJND3K0VD8TEG53M0S
			references SUPPLIERS (SUPPLIERID),
	PRODUCTID INTEGER not null
		constraint FKSYI1HWRQIKCD1IS3N7V9F2J5A
			references PRODUCTS (PRODUCTID),
	primary key (SUPPLIERID, PRODUCTID)
);

