create schema APP;

create table SUPPLIERS
(
	SUPPLIERID INTEGER not null
		primary key,
	CITY VARCHAR(255),
	COMPANYNAME VARCHAR(255),
	STREET VARCHAR(255)
);

create table PRODUCTS
(
	PRODUCTID INTEGER not null
		primary key,
	PRODUCTNAME VARCHAR(255),
	UNITSONSTOCK INTEGER not null,
	PRODUCT_FK INTEGER
		constraint FKACCSFELAACV8O55RWW68FG7KF
			references SUPPLIERS
);

