create schema APP;

create table CATEGORY
(
	CATEGORYID INTEGER not null
		primary key,
	NAME VARCHAR(255)
);

create table PRODUCTS
(
	PRODUCTID INTEGER not null
		primary key,
	PRODUCTNAME VARCHAR(255),
	UNITSONSTOCK INTEGER not null,
	CATEGORYID INTEGER
		constraint FKMGOP3YOCT41Q8YD7DPFMYI1EN
			references CATEGORY
);

create table SUPPLIERS
(
	SUPPLIERID INTEGER not null
		primary key,
	CITY VARCHAR(255),
	COMPANYNAME VARCHAR(255),
	STREET VARCHAR(255)
);

create table PRODUCTSUPPLIER
(
	SUPPLIERID INTEGER not null
		constraint FKHVXVPX6PJND3K0VD8TEG53M0S
			references SUPPLIERS,
	PRODUCTID INTEGER not null
		constraint FKSYI1HWRQIKCD1IS3N7V9F2J5A
			references PRODUCTS,
	primary key (SUPPLIERID, PRODUCTID)
);

